name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_project:
    name: Sample CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
      - name: Install dependencies
        run: flutter pub get
        working-directory: cabs/apps
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test
        working-directory: cabs/apps
      - name: Build App Bundle
        run: flutter build appbundle --release
        working-directory: cabs/apps
      - name: Build iOS (optional)
        if: runner.os == 'macOS'
        run: flutter build ios --release
        working-directory: cabs/apps
